language: python
os: ubuntu
python:
  - '3.7'
install:
  - pip install pipenv
  - pipenv install
  - ls

script:
  - pipenv run coverage run --source=b166erobot/regex-search/regex_source -m unittest discover -s b166erobot/regex-search/tests/
