language: python
os: ubuntu
python:
  - '3.7'
install:
  - pip install pipenv
  - pipenv install
  - pipenv install coverage

script:
  - pipenv shell
  - coverage run --source=regex_source -m unittest discover -s tests/
